name: Greyweathers Press
favicon: null
layout_spectrum: 0.75128
typography_spectrum: 0.8763441
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030301'
    - '#ffffff'
    - '#6f6f6d'
    - '#acadb1'
    - '#4e473d'
  brandStrength: 0.07379977847449481
  lightness: 0.6447614314965904
  saturation: 0.7224597814492881
  rhythmicContrast: 0.6527247305493802
purpose: []
