name: Greyweathers Press
favicon: null
layout_spectrum: 0.65903
typography_spectrum: 0.8763441
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#4d4e49'
    - '#7a2908'
    - '#97989c'
    - '#c9d9e6'
  brandStrength: 0.07379977847449481
  lightness: 0.6447614314965904
  saturation: 0.7224597814492881
  rhythmicContrast: 0.6527247305493802
purpose: []
