title: GREYWEATHERS
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7224597814492881
  brandStrength: 0.07379977847449481
  rhythmicContrast: 0.6527247305493802
  brandColors:
    - '#010101'
    - '#4d4e49'
    - '#7a2908'
    - '#97989c'
    - '#c9d9e6'
  lightness: 0.6447614314965904
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: GREYWEATHERS PRESS
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8763441
layout_spectrum: 0
